### ISSUE TITLE
Shipping Media/Badges

### ISSUE THREAD

**Issue by cornehoskam** [prjseal/Umbraco-Community-Quiz#11]
Hi Paul!

While pulling down the repository, I noticed that you weren't shipping any media files with your repository, even though they are serialized using uSync! Therefor things like badges aren't visible locally. Is there a possibility to ship these within git? 🙂

Kind regards,
Corné

**Comment by prjseal** [comment]
Hi Corné

You are right, I will add them to git, it won't take long to push them up.

**Comment by prjseal** [comment]
@cornehoskam I've added the media for you

**Comment by cornehoskam** [comment]
Much appreciated @prjseal!
