### ISSUE TITLE
Member quiz history chart

### ISSUE THREAD

**Issue by prjseal** [prjseal/Umbraco-Community-Quiz#19]
Create a chart that shows the member's quiz history. Show this on the member profile page above my badges next to the new member summary card. Use a view component for this

**Comment by RyanHelmn** [comment]
I quite like the sound of this one if nobody is actively looking into it :)

**Comment by prjseal** [comment]
@RyanHelmn Yeah go for it mate, no one else is working on it. 

Here's a link to an example using the same theme and assets https://demos.creative-tim.com/argon-dashboard-pro/pages/ecommerce/overview.html

**Comment by prjseal** [comment]
Hi @RyanHelmn as I didn't recieve a hacktoberfest PR for this from you, I assume you didn't get chance to do it. I have implemented it myself now. So I'm closing this issue.
