### ISSUE TITLE
Build delete profile functionality

### ISSUE THREAD

**Issue by prjseal** [prjseal/Umbraco-Community-Quiz#21]
Add a page to the member dashboard where the user can tick a box and press a button to delete their profile. This will delete everything about them from the system including their profile image, quiz results and notifications but not questions they have set.

**Comment by TECKSPEED** [comment]
Paul, if you don't mind I will pick this one up, among some others as time sees fit.

**Comment by prjseal** [comment]
Yeah go for it. Thanks mate. Please keep them in separate branches.

**Comment by prjseal** [comment]
Great to hear. Looking forward to seeing it 🤞🏻

**Comment by TECKSPEED** [comment]
@prjseal One quick question for you, using sql lite nothing special needs configuring correct? For some odd reason deleting is causing a table lock regardless of the method in which you try to delete when using the NPoco Object.

There is no specific app setting or configuration value I need set correct? 

For reference: **SQLite Error 6: 'database table is locked: QuizResult**

**Comment by prjseal** [comment]
This might be something we don't need to worry about when it is live. SQLite only allows one transaction at a time. It could be that constraint getting in the way.

If you think the logic is sound I'm happy for you to submit your PR and I can test it on Big SQL

**Comment by TECKSPEED** [comment]
Ah, understood, yeah I think the logic is sound, but was just trying to proof the changes before submitting the PR.

Let me submit the PR and we can address any issues (hopefully none as they pop up)

**Comment by prjseal** [comment]
Fixed in #43
