### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by prjseal** [prjseal/Umbraco-Community-Quiz#22]
Create password reset functionality

**Comment by NikRimington** [comment]
Oh, I don't mind looking into this :-)

**Comment by TECKSPEED** [comment]
Discord notifications to the member? Perhaps if they are apart of the Umbraco Discord?

Otherwise email or some other manner

Just an idea...

**Comment by TECKSPEED** [comment]
@NikRimington have you picked this up?

**Comment by NikRimington** [comment]
Hey @TECKSPEED yeah this is in progress at the minute :-)

**Comment by TECKSPEED** [comment]
Awesome, just making sure!

**Comment by prjseal** [comment]
Fixed in #54
