### ISSUE TITLE
Badge list page

### ISSUE THREAD

**Issue by prjseal** [prjseal/Umbraco-Community-Quiz#35]
Edit the template for the badge list page to show all badges you can get

**Comment by TECKSPEED** [comment]
@prjseal were you thinking of having this as its own page, or to show a list of possible badges on the "My Badges" screen when viewing your profile?

**Comment by prjseal** [comment]
@TECKSPEED there is already a separate page in the tree structure. I thought it would be good to show all possible badges on here. It can look like the my badges page but show all badges if you see what i mean. Should be an easy one. view component for all badges and then call that from the template which already exists but isn't implemented yet

**Comment by TECKSPEED** [comment]
@prjseal ill take this one off the table for you.

**Comment by prjseal** [comment]
Closed as completed now.
