### ISSUE TITLE
Content app to show used questions for a quiz

### ISSUE THREAD

**Issue by prjseal** [prjseal/Umbraco-Community-Quiz#39]
The quiz page has a question picker on it and you can only pick questions that are set to approved. Once a question is used we change the status of the question to used. This means the questions don't show up in the question picker anymore but they are still there on that quiz. We could do with a content app that just shows the list of questions that were used on that quiz.

**Comment by OwainWilliams** [comment]
I can have a look at this @prjseal :)

**Comment by prjseal** [comment]
Ooh yes please 🙂

**Comment by prjseal** [comment]
fixed in #52
