### ISSUE TITLE
Update Security Headers

### ISSUE THREAD

**Issue by mattou07** [prjseal/Umbraco-Community-Quiz#42]
![image](https://user-images.githubusercontent.com/11179749/196184672-bb53fd72-9aa6-4b71-8cab-7c7061e9df88.png)

Site does not implement the recommended security headers such as Content Security etc: https://securityheaders.com/?q=communityquiz.net&followRedirects=on

**Comment by mattou07** [comment]
Looking into this now

**Comment by prjseal** [comment]
Fixed in #45
