### ISSUE TITLE
Week 3 Question: Which Database type is not supported in Umbraco 10?

### ISSUE THREAD

**Issue by cornehoskam** [prjseal/Umbraco-Community-Quiz#49]
Hi @prjseal, just double checking something in this week's quiz, as I think there might be a wrong question/answer going on in Week 3's quiz!

![image](https://user-images.githubusercontent.com/6321978/197530300-b54aa156-6828-42ba-9867-088705c36786.png)

The learn more link goes to a[ Removal of MySQL link](https://github.com/umbraco/Umbraco-CMS/pull/4143/files), which isn't a valid answer, and if you were to check out the following link, it specifies that it's LocalDB that is no longer supported, not SqlCE, or am I forgetting something? 😇

https://our.umbraco.com/documentation/Umbraco-Cloud/Databases/Local-Database/#connecting-to-your-local-umbraco-installation

**Comment by prjseal** [comment]
It was gonna be MySQL then I changed it to sqlce. I forgot to find a link for it. I will double check

**Comment by prjseal** [comment]
I've updated the link to be this. https://umbraco.com/blog/umbraco-10-release/
The answer is correct. SQL CE was replaced by SQLite
