### ISSUE TITLE
Can't view another persons profile

### ISSUE THREAD

**Issue by mattou07** [prjseal/Umbraco-Community-Quiz#55]
Its not clear or possible to visit another persons profile to see their badges or stats.

**Comment by prjseal** [comment]
You're right @mattou07 I created a feature in preparation for this. You can now hide your profile so it doesn't show in the leaderboard. And when we implement the ability to click on profiles we will check if the user wants to be hidden or not first before returning the content. It's not been built yet, but I will probably pick this up myself unless someone else wants to work on it

**Comment by prjseal** [comment]
Fixed now https://communityquiz.net/profile/?memberId=2747
