### ISSUE TITLE
Broken link in Week 8 Quiz

### ISSUE THREAD

**Issue by sofietoft** [prjseal/Umbraco-Community-Quiz#64]
When catching up on these quizzes, I found a broken link:
The docs link for question 1 in Week 8 🙈 
https://communityquiz.net/quizzes/week-8/#question1

The link: https://our.umbraco.com/Documentation/Extending/Key-Vault#link-our-key-vault-secret-to-an-azure-web-app 

This should instead be: https://docs.umbraco.com/umbraco-cms/extending/key-vault#link-our-key-vault-secret-to-an-azure-web-app 💪

**Comment by sofietoft** [comment]
Same for Question 2: https://communityquiz.net/quizzes/week-8/#question2

I'll add a redirect to Our, as we removed this article entirely from there, I can see!

**Comment by prjseal** [comment]
Fixed, thank you very much for letting me know
